# Generated by Django 6.0 on 2025-12-20 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sr_nature',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('open', 'Open'), ('wip', 'Work In Progress'), ('closed', 'Closed')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SR Status',
                'verbose_name_plural': 'SR Statuses',
            },
        ),
        migrations.CreateModel(
            name='SRType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sr_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(db_column='sr_number', db_index=True, editable=False, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('parented', 'Parented SR'), ('unparented', 'Unparented SR')], db_column='category', help_text='Whether the request is Parented (linked to account) or Unparented.', max_length=20)),
                ('subject', models.CharField(db_column='subject', help_text='Brief subject of the service request', max_length=200)),
                ('description', models.TextField(db_column='description', help_text='Detailed description of the issue or request')),
                ('account_number', models.CharField(blank=True, db_column='account_number', db_index=True, help_text='Associated account number (for Parented SRs).', max_length=20, null=True)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('phone', models.CharField(db_column='phone', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('closed_at', models.DateTimeField(blank=True, db_column='closed_at', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_created', to=settings.AUTH_USER_MODEL)),
                ('sr_nature', models.ForeignKey(db_column='sr_nature', on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_request.srnature')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_request.srstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SRComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes not visible to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service_request.servicerequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SR Comment',
                'verbose_name_plural': 'SR Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SRTATDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_nature', models.CharField(choices=[('complaint', 'Complaint'), ('request', 'Request'), ('query', 'Query')], max_length=20)),
                ('sr_type', models.CharField(choices=[('card_issue', 'Card Issue'), ('netbanking_issue', 'NetBanking Issue'), ('branch_service', 'Branch Service'), ('loan_related', 'Loan Related'), ('account_opening', 'Account Opening'), ('transaction_dispute', 'Transaction Dispute'), ('others', 'Others')], max_length=30)),
                ('tat_days', models.PositiveIntegerField(help_text='TAT in days')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SR TAT (Days)',
                'verbose_name_plural': 'SR TATs (Days)',
                'unique_together': {('sr_nature', 'sr_type')},
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tat',
            field=models.ForeignKey(blank=True, db_column='tat', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_request.srtatdays'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='sr_type',
            field=models.ForeignKey(db_column='sr_type', on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service_request.srtype'),
        ),
    ]
